In [2]:
from numpy import *

In [5]:
ar = array( [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9] ] )

In [6]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
sl= ar[0,1:3]
sl

array([2, 3])

In [14]:
sl= ar[0:3,0:3:2] # start:end:step
sl

array([[1, 3],
       [4, 6],
       [7, 9]])

In [35]:
newArray = ar[:,[0,2]] # all rows and coloms which indesx are 0 and 2
newArray

array([[1, 3],
       [4, 6],
       [7, 9]])

In [16]:
a = arange(10) 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
s = slice(2,7,2)
a[s]

array([2, 4, 6])

In [19]:
a = arange(10) # start:end:step
b = a[2:7:2]
b

array([2, 4, 6])

In [34]:
a = array([[1,2,3],
           [3,4,5],
           [4,5,6]])  
print(a)
# slice items starting from index
print ('Now we will slice the array from the index a[1:]') 
a[1:] # ==  a[1: , : ]

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]


array([[3, 4, 5],
       [4, 5, 6]])

In [44]:
x = arange(25).reshape(5,5)
print(x.shape)
print(x.ndim)
x

(5, 5)
2


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
x = zeros((5,5))
y = ones((5,5))
print (x)
print (y)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
z = eye(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a = arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [58]:
test = random.randint(0, 10, (4,3))
test

array([[9, 5, 5],
       [6, 1, 3],
       [6, 5, 9],
       [1, 3, 1]])

In [60]:
ar = arange(0,36)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [61]:
ar.reshape(6,6)   # slice the diagonal

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [62]:
ar.reshape(36) # step 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [63]:
ar[::7] #step 2

array([ 0,  7, 14, 21, 28, 35])

In [69]:
m = array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = empty_like(m)
print('result')
print(result)
print()
for i in range(4):
  result[i, :] = m[i, :]+ v  
  print(result)
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)

Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
result
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 2  3  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  3  3]
 [ 5  6  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [10 11 12]]
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


In [70]:
m = array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = array([dot(row,v)for row in m])
print('result')
print(result)

Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
result
[ 3  9 15 21]


In [83]:
arr = arange(1,31)  # aar is object from class arange
arr=arr.reshape(6,5) #reshape is a method from that class
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [85]:
arr[[0,1],[1,2]]

array([2, 8])

         0   1   2   3   4
      0[ 1,  2,  3,  4,  5],
      1[ 6,  7,  8,  9, 10],
      2[11, 12, 13, 14, 15],
      3[16, 17, 18, 19, 20],
      4[21, 22, 23, 24, 25],
      5[26, 27, 28, 29, 30]])



In [87]:
arr[[0,1,2,3,4],[0,1,2,3,4]] 

array([ 1,  7, 13, 19, 25])

In [88]:
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])